name: env_configurator
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/vzotech/env_configurator
author: mahmed <mahmed8003@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.5.2
  colorize: ^2.0.0
  yaml: ^2.2.0
  xml: ^3.5.0
  recase: ^2.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
