name: env_configurator
description: A package to manage configuration variables and configuration files on flutter and native platforms level
version: 0.3.0
homepage: https://github.com/vzotech/env_configurator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.2.0
  colorize: ^3.0.0
  yaml: ^3.1.0
  xml: ^5.1.2
  recase: ^4.0.0

dev_dependencies:
  test: ^1.17.4

