name: env_configurator
description: A package to manage configuration variables and configuration files on flutter and native platforms level
version: 0.3.0
homepage: https://github.com/vzotech/env_configurator

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  yaml: ^3.1.2
  xml: ^6.5.0
  recase: ^4.1.0

dev_dependencies:
  test: ^1.25.0

